version: "3.9"

services:
  chatbot-api:
    build:
      context: .
    container_name: chatbot-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
